Lvl up
Teaching-projects/-SZE-MOSZE-2020-BDFANS pull request #5
Opened 2020-10-15 19:45 UTC by LuczaDennis

2020-10-21 21:55 UTC, oliverosz requested changes
A javítások rendesen, gittel legyenek commitolva, ne a böngészőben szerkesztve.

2020-10-21 21:55 UTC, oliverosz commented on .github/workflows/memtest.yml
> +            - run: valgrind --track-origins=yes ./battle Units/a.txt Units/b.txt
Ez a 3 parancs most csak kiírja a hibákat, de ettől még a workflow megkapja a pipát.
A fordító kapjon egy `-Werror` paramétert. A cppcheck egy `--error-exitcode=1`-et, ugyanezt a valgrind is, csak ott kell még egy `--leak-check=full` is. Ezen kívül a feladatban szerepelt az is, hogy a (cppcheck által jelzett) style és performance figyelmeztetések legyenek artifactolva.

2020-10-21 21:55 UTC, oliverosz commented on Unit.cpp
> +#include <math.h>
`<cmath>`

2020-10-21 21:55 UTC, oliverosz commented on Battle.cpp
> +	Unit Tdefender = defender;
Miért másolatok harcolnak?

2020-10-21 21:55 UTC, oliverosz commented on Battle.cpp
> +			attacker.setUnit(Tattacker);
Erre nem kell külön metódus: `attacker = Tattacker;`

2020-10-21 21:55 UTC, oliverosz commented on callgrind.out.10036
> +creator: callgrind-3.15.0
A callgrind kimenetét nem kell verziókövetni.

2020-10-24 14:46 UTC, LuczaDennis commented on Battle.cpp
> +	Unit Tdefender = defender;
Azért a másolatok harcolnak mert a feladatban úgy van leírva, hogy csak a nyertes kapja meg az exp-t. A nyertes megtartja a szerzett szinteket a vesztes meg marad a csata előtti szintjén. Így találtam a legegyszerűbbnek a megoldását.

2020-10-25 00:53 UTC, oliverosz commented
Mondtam, hogy a javítások ne böngészőben legyenek commitolva. Ez nem normális git history, hogy minden fájl külön commitban kerül változtatásra.

2020-10-25 12:18 UTC, LuczaDennis commented
Elnézést tanár úr. Windows alatt volt linux alrendszerem, ami megadta magát onnan nem tudtam commitolni. Mit lehet tenni ebben az esetben?

2020-10-25 19:52 UTC, oliverosz commented
> Elnézést tanár úr. Windows alatt volt linux alrendszerem, ami megadta magát onnan nem tudtam commitolni. Mit lehet tenni ebben az esetben?

Van Git for Windows, nem kell Linux alrendszert használni.

2020-10-26 14:31 UTC, LuczaDennis commented
> > Elnézést tanár úr. Windows alatt volt linux alrendszerem, ami megadta magát onnan nem tudtam commitolni. Mit lehet tenni ebben az esetben?
> 
> Van Git for Windows, nem kell Linux alrendszert használni.

Köszönöm. Innentől akkor azt fogom használni.

2020-10-29 21:25 UTC, oliverosz commented
Adok még egy esélyt javításra, de most már tényleg gittel legyenek csinálva a commitok.

2020-10-29 21:32 UTC, oliverosz commented on .github/workflows/memtest.yml
> +            - run: cppcheck *.cpp --enable=warning --error-exitcode=1
hiányzik az artifact

2020-10-29 21:32 UTC, oliverosz commented on Battle.cpp
> +		Tattacker.gainExp(Tattacker.attack(Tdefender));
a `gainExp`et ne kívülről kelljen hívni (ne is lehessen), az történjen meg automatikusan a támadáskor

2020-10-29 21:32 UTC, oliverosz commented on callgrind.out.10036
> +creator: callgrind-3.15.0
Továbbra se szerepeljen a verziókezelésben ez a fájl.

2020-10-29 21:34 UTC, oliverosz reviewed
Ha az említett hibák javításra kerültek, frissítsd a branchet a masterre, és oldd fel a konfliktusokat. Az attackspeeddel való egyesítésnél a szintlépéshez kerüljön be a cooldown csökkentése is.

2020-11-01 17:29 UTC, oliverosz requested changes
Az artifactolás nem jó, és a callgrind.out fájl még nem lett törölve a repóból.

2020-11-01 17:29 UTC, oliverosz commented on .github/workflows/memtest.yml
> +                 path: ./cppcheckartifact.txt
Így soha semmit nem fog feltölteni artifactként, mert az 1-es exitcode leállítja a workflow-t. És amúgy sem írja ki a style és performance hibákat, amiket artifactolni kellene.

2020-11-01 18:04 UTC, LuczaDennis commented on .github/workflows/memtest.yml
> +                 path: ./cppcheckartifact.txt
Köszönöm tanár úr! Javítottam.

2020-11-01 18:20 UTC, LuczaDennis commented on .github/workflows/memtest.yml
> +                 path: ./cppcheckartifact.txt
Csak folyamatosan elbénázok valamit.

2020-11-01 20:03 UTC, oliverosz approved these changes

2020-11-01 20:03 UTC, merged